### ISSUE TITLE
 Jinja error: unhashable type: 'list' when using "CLUSTERS"

### ISSUE THREAD

**Issue by vvden** [saltstack-formulas/zookeeper-formula#56]
Hello
Under zookeeper pillar I have:
```
  clusters:
    kafkatest:
      - test-kafka1.mytest.com
      - test-kafka2.mytest.com
      - test-kafka3.mytest.com
```
And each of the nodes has cluster_id pillar defined. 
```
salt -G 'zookeeper:cluster_id:kafkatest' test.ping
test-kafka2.mytest.com:
    True
test-kafka1.mytest.com:
    True
test-kafka3.mytest.com:
    True
```
The settings.sls has logic to check if cluster_id is defined, in which case it tries to set zookeeper_nodes to the list of cluster_id nodes. But it gives an error:

```
test-kafka3.mytest.com:
    Data failed to compile:
----------
    Rendering SLS 'base:zookeeper' failed: Jinja error: unhashable type: 'list'
/var/cache/salt/minion/files/base/zookeeper/settings.sls(84):
---
[...]
                                grains['nodename']] + salt['network.ip_addrs']() %}

{%- if p.get('nodes') %}
  {%- set zookeeper_nodes = p.nodes %}
{%- elif p.get('clusters') and cluster_id != None %}
  {%- set zookeeper_nodes = p.clusters.get(cluster_id, []) %}    <======================
{%- elif p.get('clusters') %}
  {%- if p.clusters|length == 1 %}
    {%- set zookeeper_nodes = p.clusters.values()[0] %}
  {%- else %}
    {%- set zookeeper_nodes = [] %}
[...]
---
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/templates.py", line 413, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<template>", line 1, in top-level template code
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 1013, in make_module
    return TemplateModule(self, self.new_context(vars, shared, locals))
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 1070, in __init__
    self._body_stream = list(template.root_render_func(context))
  File "/var/cache/salt/minion/files/base/zookeeper/settings.sls", line 84, in top-level template code
    {%- set zookeeper_nodes = p.clusters.get(cluster_id, []) %}
TypeError: unhashable type: 'list'

```

I don't see what I'm missing, and it appears that settings catches the fact that i have cluster setup, just fails to set the zookeeper_nodes with list of cluster nodes

**Comment by vvden** [comment]
Here's how i got it to work:
`--- a/formulas/zookeeper-formula/zookeeper/settings.sls
+++ b/formulas/zookeeper-formula/zookeeper/settings.sls
@@ -81,7 +81,7 @@
 {%- if p.get('nodes') %}
   {%- set zookeeper_nodes = p.nodes %}
 {%- elif p.get('clusters') and cluster_id != None %}
-  {%- set zookeeper_nodes = p.clusters.get(cluster_id, []) %}
+  {%- set zookeeper_nodes = p.clusters[''+cluster_id[0]] %}
`

**Comment by codeboyQ2n5ha45** [comment]
Should be able to close this as formula has been refactored.
